export const cinzaTexto = "#9e9d99"
export const cinzaClaro = "#9e9c98"
export const dourado = "#9f7f2a"
export const cinzaMaisClaro = "#d1cfce"
export const grafite = "#33302d"
export const marrom = "#442000"
export const salmao = "#ffdcbc"